site_name: Paul WILLIAMS
repo_url: https://github.com/paul58914080/my-notes
repo_name: my-notes
edit_uri: ""
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  language: en
  custom_dir: docs/overrides
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - abbreviations.md
extra_css:
  - stylesheets/bootstrap-grid.min.css
  - stylesheets/skills.css
  - stylesheets/palette.min.css
  - stylesheets/custom.css
  - stylesheets/typography.css
#  - stylesheets/main.min.css
#  - stylesheets/custom.min.css

nav:
  - About me: 'index.md'
  - Craft:
      - API first: 'pages/craft/api-first/index.md'
      - Hexagonal architecture: 'pages/craft/hexagonal-architecture/index.md'
  - Data:
      - Introduction: 'pages/data/introduction/index.md'
  - Frontend:
      - Scaffold angular: 'pages/frontend/scaffold-angular/index.md'
      - Testing angular: 'pages/frontend/testing-angular/index.md'
      - RxJS: 'pages/frontend/rxjs/index.md'
      - Micro frontend: 'pages/frontend/micro-frontend/index.md'
  - Backend:
      - Scaffold hexagon spring-boot: 'pages/backend/scaffold-hexagon-spring-boot/index.md'
  - DevOps:
      - Docker: 'pages/devops/docker/index.md'
      - Distroless images: 'pages/devops/distroless-images/index.md'
      - Github actions: 'pages/devops/github-actions/index.md'
  - Mac:
      - Homebrew: 'pages/mac/homebrew/index.md'
  - Tools:
      - Git: 'pages/tools/git/index.md'
      - SDKMAN: 'pages/tools/sdkman/index.md'
      - JDK: 'pages/tools/jdk/index.md'
      - Maven: 'pages/tools/maven/index.md'
      - Gradle: 'pages/tools/gradle/index.md'
      - Node: 'pages/tools/node/index.md'
      - Yarn: 'pages/tools/yarn/index.md'
  - Tips & Tricks:
      - Beautify terminals: 'pages/tips-and-tricks/beautify-terminal/index.md'
      - IntelliJ: 'pages/tips-and-tricks/intellij/index.md'
